// src/lib/images.ts
//
// Central image-slot registry. The WebP files live in /public/images/
// and are generated by scripts/download-and-process-images.mjs. Each slot
// knows its own widths, so React components can just ask for `getImage(slot)`
// and drop the result onto a native <img> tag.
//
// All slot names match the files on disk. Do not hand-edit.

export type HeroSlot =
  | 'hero-aurora'
  | 'hero-dusk-lake';

export type TripSlot =
  | 'trip-aurora-chase'
  | 'trip-cabin-life'
  | 'trip-food'
  | 'trip-forest-walk'
  | 'trip-night-forest'
  | 'trip-silence'
  | 'trip-solo-trek';

export type PillarSlot =
  | 'pillar-cold'
  | 'pillar-shelter'
  | 'pillar-people';

export type CategorySlot =
  | 'category-aurora'
  | 'category-cabins'
  | 'category-food'
  | 'category-seasons';

export type AsideSlot = 'aside-vesa';

export type ImageSlot =
  | HeroSlot
  | TripSlot
  | PillarSlot
  | CategorySlot
  | AsideSlot;

type ImageMeta = {
  sizes: number[];    // widths available on disk, largest first
  ratio: '21:9' | '3:2';
  alt: string;        // default alt — components may override
};

// Keep order consistent with scripts/download-and-process-images.mjs
const REGISTRY: Record<ImageSlot, ImageMeta> = {
  'hero-aurora': {
    sizes: [2560, 1920, 1200],
    ratio: '21:9',
    alt: 'Green aurora borealis arching over a winding frozen river in Lapland',
  },
  'hero-dusk-lake': {
    sizes: [2560, 1920, 1200],
    ratio: '21:9',
    alt: 'Frozen lake in Lapland at blue-hour dusk, snow-covered pines along the shore',
  },

  'trip-aurora-chase': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Massive green aurora over broken ice floes on a frozen sea',
  },
  'trip-cabin-life': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Warm-lit log cabin at night with footprints in fresh snow',
  },
  'trip-food': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Bowl of Finnish salmon soup with dill, rye bread and a curl of butter',
  },
  'trip-forest-walk': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Backpacker walking through a snow-covered pine forest at golden hour',
  },
  'trip-night-forest': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Snow-draped spruce forest at night under a starry sky',
  },
  'trip-silence': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'A single snow-covered pine on a frozen lake at twilight',
  },
  'trip-solo-trek': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Solo hiker disappearing into a quiet forest trail at sunset',
  },

  'pillar-cold': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'A snow-covered city bench under a lit apartment window on a frozen night',
  },
  'pillar-shelter': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Log cabin by a frozen lake at sunrise with smoke rising from its chimney',
  },
  'pillar-people': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Weathered hands cradling a steaming enamel mug by a frozen river',
  },

  'category-aurora': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Dark snowy forest with a faint green aurora glow on the horizon',
  },
  'category-cabins': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Cabin interior with wood stove, folded wool blankets and a steaming mug',
  },
  'category-food': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Slate board with salmon, cloudberries, lingonberries and crispbread',
  },
  'category-seasons': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'Solitary birch tree split half summer / half winter',
  },

  'aside-vesa': {
    sizes: [1200, 800, 480],
    ratio: '3:2',
    alt: 'A tiny figure with a headlamp standing under a giant aurora arc over Lapland tundra',
  },
};

export type ResolvedImage = {
  /** URL of the largest available size — use this as <img src>. */
  src: string;
  /** Full `srcset` string with every available size. */
  srcSet: string;
  /** Matching `sizes` attribute hint. */
  sizes: string;
  /** Alt text for accessibility. */
  alt: string;
  /** Aspect ratio helper for CSS (e.g. "3 / 2"). */
  aspectRatio: string;
};

/**
 * Resolve an image slot into attributes you can drop straight onto `<img>`.
 * @param slot     slot name registered above
 * @param sizesHint optional custom `sizes` string (defaults to full-width)
 * @param altOverride optional alt to use instead of the registry default
 */
export function getImage(
  slot: ImageSlot,
  sizesHint?: string,
  altOverride?: string
): ResolvedImage {
  const meta = REGISTRY[slot];
  const sorted = [...meta.sizes].sort((a, b) => b - a); // largest first
  const largest = sorted[0];

  const srcSet = sorted
    .map((w) => `/images/${slot}-${w}.webp ${w}w`)
    .join(', ');

  const defaultSizes =
    meta.ratio === '21:9'
      ? '(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 1600px'
      : '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';

  return {
    src: `/images/${slot}-${largest}.webp`,
    srcSet,
    sizes: sizesHint ?? defaultSizes,
    alt: altOverride ?? meta.alt,
    aspectRatio: meta.ratio === '21:9' ? '21 / 9' : '3 / 2',
  };
}

/** For `<link rel="preload">` in <head> — returns just the largest URL. */
export function getImagePreloadSrc(slot: ImageSlot): string {
  const meta = REGISTRY[slot];
  const largest = [...meta.sizes].sort((a, b) => b - a)[0];
  return `/images/${slot}-${largest}.webp`;
}
