import { useParams, Link, Navigate } from 'react-router-dom';
import { useEffect, useMemo } from 'react';
import { ArrowLeft, Clock, Calendar, PenLine } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import Nav from '../components/Nav';
import Footer from '../components/Footer';
import Newsletter from '../components/Newsletter';
import ReadingProgress from '../components/ReadingProgress';
import TableOfContents from '../components/TableOfContents';
import AuthorBio from '../components/AuthorBio';
import PostCard from '../components/PostCard';
import Reveal from '../components/Reveal';
import ShareBar from '../components/ShareBar';
import BannerAd from '../components/BannerAd';
import HighlightShare from '../components/HighlightShare';
import type { PostBlock } from '../data/posts';
import { categoryBySlug } from '../data/categories';
import { useSeo, canonicalUrl } from '../lib/seo';
import {
  useJsonLd,
  blogPostingSchema,
  breadcrumbSchema,
} from '../lib/jsonld';
import { trackPostRead } from '../lib/analytics';
import { generateHashtags, formatHashtags } from '../lib/hashtags';
import { detectCrossSiteLinks } from '../lib/crossSiteLinks';
import { usePost, useRelated } from '../hooks/usePost';
import { useLang, useLocalePath } from '../i18n/useLang';
import { COPY } from '../locales/copy';

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

/**
 * Render a single content block. H2s receive anchor ids derived from index
 * so the TableOfContents can link to them.
 */
function Block({ block, index }: { block: PostBlock; index: number }) {
  switch (block.type) {
    case 'paragraph':
      return <p>{block.text}</p>;
    case 'heading': {
      const id = `h-${index}`;
      if (block.level === 2) return <h2 id={id}>{block.text}</h2>;
      return <h3 id={id}>{block.text}</h3>;
    }
    case 'pullquote':
      return <blockquote className="pullquote">{block.text}</blockquote>;
    case 'divider':
      return <hr />;
    case 'list':
      if (block.ordered) {
        return (
          <ol>
            {block.items.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ol>
        );
      }
      return (
        <ul>
          {block.items.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      );
    case 'image':
      return (
        <figure className={block.full ? 'figure-full' : undefined}>
          <img src={block.src} alt={block.alt} loading="lazy" decoding="async" />
          {block.caption && <figcaption>{block.caption}</figcaption>}
        </figure>
      );
    case 'markdown':
      return (
        <div className="markdown-block">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{block.text}</ReactMarkdown>
        </div>
      );
    default:
      return null;
  }
}

export default function Post() {
  const lang = useLang();
  const to = useLocalePath();
  const c = COPY[lang].post;
  const { slug } = useParams<{ slug: string }>();
  const { post, loading, notFound } = usePost(slug);
  const { related } = useRelated(post?.slug, post?.category, 2);

  // Generate hashtags for the post (brand + category + location-detected)
  const hashtags = post
    ? generateHashtags(post.category, post.content)
    : [];
  const hashtagString = formatHashtags(hashtags);

  // Detect contextual cross-site links from post content
  const crossSiteLinks = useMemo(() => {
    if (!post) return [];
    const text = post.content
      .map((b) => ('text' in b ? b.text : 'items' in b ? b.items.join(' ') : ''))
      .join(' ');
    return detectCrossSiteLinks(text);
  }, [post]);

  // Hooks must always run — move them above the early return.
  // Branded 1200×630 OG card (generated by scripts/generate-og-images.mjs) for
  // the seed posts; user-written posts fall back to their own hero image.
  const SEED_OG_SLUGS = new Set([
    'the-night-the-sky-broke-open-over-kemi',
    'why-i-stopped-chasing-the-aurora-with-an-app',
    'five-nights-in-a-forest-cabin',
    'a-bowl-of-salmon-soup-that-cost-more-than-the-flight',
    'living-between-two-suns',
  ]);
  const ogImage = post
    ? SEED_OG_SLUGS.has(post.slug)
      ? `https://lapland.blog/og/${post.slug}.jpg`
      : post.heroImage
    : undefined;
  useSeo({
    title: post ? `${post.title} · Lapland.blog` : 'Loading · Lapland.blog',
    description: post?.excerpt ?? 'Story on Lapland.blog',
    image: ogImage,
    canonical: post ? canonicalUrl(`/post/${post.slug}`) : canonicalUrl('/'),
    type: post ? 'article' : 'website',
    publishedAt: post?.publishedAt,
    modifiedAt: post?.publishedAt,
    author: 'The Field Journal',
    tags: post?.tags ? [...post.tags, ...hashtags] : hashtags,
  });

  useJsonLd(
    'post',
    post
      ? [
          blogPostingSchema(post),
          breadcrumbSchema([
            { name: 'Home', url: canonicalUrl('/') },
            { name: 'Stories', url: canonicalUrl('/stories') },
            {
              name: categoryBySlug(post.category)?.name ?? 'Story',
              url: canonicalUrl(`/category/${post.category}`),
            },
            { name: post.title, url: canonicalUrl(`/post/${post.slug}`) },
          ]),
        ]
      : null
  );

  useEffect(() => {
    if (post) trackPostRead(post.slug, post.title, post.category);
  }, [post]);

  // Loading state — don't flash 404 while Supabase is still fetching.
  if (loading) {
    return (
      <div className="theme-editorial min-h-screen">
        <Nav />
        <div className="pt-40 pb-40 px-4 text-center">
          <div className="inline-block w-6 h-6 border-2 border-[var(--color-accent)] border-t-transparent rounded-full animate-spin" />
          <p className="mt-4 text-[var(--color-ink-mute)] text-sm">{c.loadingStory}</p>
        </div>
      </div>
    );
  }

  if (notFound || !post) {
    return <Navigate to="/404" replace />;
  }

  const cat = categoryBySlug(post.category);

  return (
    <div className="theme-editorial min-h-screen">
      <Nav />
      <ReadingProgress />

      {/* ================================================================
          HERO — full-bleed image, centred title plate, refined crop.
          A modern long-read masthead: the image breathes full width, the
          title sits on a cream plate that overlaps it, with a soft top scrim
          so the eyebrow + back-link stay legible on any photo.
          ================================================================ */}
      <header className="relative pt-16">
        <div className="relative h-[64vh] min-h-[440px] max-h-[720px] overflow-hidden bg-[var(--color-cream-deep)]">
          <img
            src={post.heroImage}
            alt={post.heroAlt}
            className="absolute inset-0 w-full h-full object-cover object-[50%_42%]"
            fetchPriority="high"
            decoding="async"
          />
          {/* Top scrim for the floating back-link; bottom fade into the plate. */}
          <div className="absolute inset-0 bg-gradient-to-b from-black/45 via-transparent to-black/35" />

          <div className="absolute top-0 inset-x-0 px-4 sm:px-6 lg:px-8 pt-5">
            <div className="max-w-[72rem] mx-auto">
              <Link
                to={to('/stories')}
                className="inline-flex items-center gap-1.5 text-white/90 hover:text-white text-xs uppercase tracking-[0.25em] font-semibold transition-colors hero-text-shadow-sm"
              >
                <ArrowLeft size={14} /> {c.allStories}
              </Link>
            </div>
          </div>
        </div>

        {/* Title plate — overlaps the hero image, centred reading column. */}
        <div className="relative px-4 sm:px-6 lg:px-8 -mt-28 md:-mt-36 mb-10">
          <div className="max-w-[52rem] mx-auto">
            <div className="bg-[var(--color-cream)] rounded-[1.25rem] shadow-[0_50px_90px_-50px_rgba(0,0,0,0.55)] border border-[var(--color-paper-border)] px-6 py-10 md:px-14 md:py-14">
              {cat && (
                <Link
                  to={to(`/category/${cat.slug}`)}
                  className="inline-flex items-center gap-2 text-[var(--color-accent)] text-[11px] uppercase tracking-[0.32em] font-bold mb-5 hover:text-[var(--color-accent-dark)] transition-colors"
                >
                  <span className="w-6 h-px bg-[var(--color-accent)]/50" />
                  {cat.name} · {post.kicker}
                </Link>
              )}

              <h1
                className="text-[var(--color-ink)] leading-[1.06] tracking-[-0.015em] text-[clamp(2.1rem,5.5vw,3.75rem)]"
                style={{ fontFamily: 'var(--font-editorial)', fontWeight: 800 }}
              >
                {post.title}
              </h1>

              <p className="mt-6 text-[var(--color-ink-soft)] text-lg md:text-[1.3rem] leading-relaxed">
                {post.excerpt}
              </p>

              <div className="mt-8 pt-6 border-t border-[var(--color-paper-border)] flex flex-wrap items-center gap-x-5 gap-y-3 text-sm text-[var(--color-ink-mute)]">
                <span className="inline-flex items-center gap-2.5">
                  <span
                    className="w-9 h-9 rounded-full bg-[var(--color-accent)] text-white flex items-center justify-center text-[11px] font-bold"
                    aria-hidden="true"
                  >
                    FJ
                  </span>
                  <span>
                    {c.by}{' '}
                    <Link
                      to={to('/about')}
                      className="text-[var(--color-ink)] font-semibold hover:text-[var(--color-accent)] transition-colors"
                    >
                      The Field Journal
                    </Link>
                  </span>
                </span>
                <span className="inline-flex items-center gap-1.5">
                  <Calendar size={14} />
                  <time dateTime={post.publishedAt}>{formatDate(post.publishedAt)}</time>
                </span>
                <span className="inline-flex items-center gap-1.5">
                  <Clock size={14} />
                  {post.readTimeMinutes} {c.minRead}
                </span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* ================================================================
          ARTICLE BODY with sticky TOC + ad rail.
          The body is a centred ~65ch measure; the rail floats to its right on
          xl. Full-bleed figures inside the prose break the measure for impact.
          ================================================================ */}
      <main className="px-4 sm:px-6 lg:px-8 pb-24">
        <div className="max-w-[72rem] mx-auto">
          {/* Editorial framing — transparent attribution (honest model). */}
          <div className="max-w-[65ch] mx-auto mb-10 flex items-start gap-3 rounded-xl border border-[var(--color-paper-border)] bg-[var(--color-cream-deep)] px-5 py-4">
            <PenLine size={16} className="text-[var(--color-accent)] shrink-0 mt-0.5" />
            <p className="text-[var(--color-ink-soft)] text-[0.9rem] leading-relaxed">
              <span className="font-semibold text-[var(--color-ink)]">{c.editorialLabel}.</span>{' '}
              {c.editorialNote}
            </p>
          </div>

          <div className="xl:grid xl:grid-cols-[minmax(0,1fr)_256px] xl:gap-14">
            <div id="post-body" className="prose-editorial">
              {post.content.map((block, i) => (
                <Block key={i} block={block} index={i} />
              ))}
            </div>
            <aside className="hidden xl:flex xl:flex-col xl:gap-8 xl:sticky xl:top-24 xl:self-start">
              <TableOfContents blocks={post.content} />
              <BannerAd partner="hotels" sid="post_sidebar_hotels" destination="Lapland" />
            </aside>
          </div>
          <HighlightShare
            containerSelector="#post-body"
            url={canonicalUrl(`/post/${post.slug}`)}
            slug={post.slug}
          />

          {/* Auto-generated hashtags — always visible */}
          {hashtags.length > 0 && (
            <div className="max-w-[65ch] mx-auto mt-14 pt-8 border-t border-[var(--color-paper-border)]">
              <div className="flex flex-wrap gap-2">
                {hashtags.map((tag) => (
                  <span
                    key={tag}
                    className="px-3 py-1.5 rounded-full text-xs font-semibold text-[var(--color-accent)] bg-[var(--color-accent)]/8 border border-[var(--color-accent)]/20 transition-colors hover:bg-[var(--color-accent)]/15"
                  >
                    #{tag}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Contextual cross-site links — auto-detected from content */}
          {crossSiteLinks.length > 0 && (
            <div className="max-w-[65ch] mx-auto mt-10 rounded-2xl border border-[var(--color-paper-border)] bg-[var(--color-cream-deep)] p-6">
              <p className="text-[10px] uppercase tracking-[0.3em] text-[var(--color-accent)] font-bold mb-4">
                {c.exploreMore}
              </p>
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {crossSiteLinks.map((link) => (
                  <a
                    key={link.site}
                    href={link.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group flex flex-col gap-1.5 rounded-xl border border-[var(--color-paper-border)] bg-[var(--color-cream)] p-4 hover:border-[var(--color-accent)] hover:shadow-sm transition-all"
                  >
                    <span className="text-sm font-semibold text-[var(--color-ink)] group-hover:text-[var(--color-accent)] transition-colors">
                      {link.label}
                    </span>
                    <span className="text-xs text-[var(--color-ink-mute)] leading-snug">
                      {link.description}
                    </span>
                  </a>
                ))}
              </div>
            </div>
          )}

          <ShareBar slug={post.slug} title={post.title} excerpt={post.excerpt} hashtags={hashtagString} />

          {/* Tags row */}
          {post.tags.length > 0 && (
            <div className="max-w-[65ch] mx-auto mt-14 pt-8 border-t border-[var(--color-paper-border)]">
              <p className="text-[10px] uppercase tracking-[0.3em] text-[var(--color-ink-mute)] mb-3 font-semibold">
                {c.tagged}
              </p>
              <div className="flex flex-wrap gap-2">
                {post.tags.map((tag) => (
                  <span
                    key={tag}
                    className="px-3 py-1 rounded-full text-xs text-[var(--color-ink-soft)] bg-[var(--color-cream-deep)] border border-[var(--color-paper-border)]"
                  >
                    #{tag}
                  </span>
                ))}
              </div>
            </div>
          )}

          <AuthorBio variant="editorial" />
        </div>
      </main>

      {/* ================================================================
          READ NEXT — bridge: cream cards on cream bg
          ================================================================ */}
      {related.length > 0 && (
        <section className="px-4 sm:px-6 lg:px-8 pb-24 bg-[var(--color-cream-deep)] py-20">
          <div className="max-w-[68rem] mx-auto">
            <Reveal>
              <p className="text-[var(--color-accent)] text-[10px] uppercase tracking-[0.35em] font-bold mb-3">
                {c.readNextEyebrow}
              </p>
              <h2
                className="text-[var(--color-ink)] text-3xl md:text-4xl font-normal mb-10"
                style={{ fontFamily: 'var(--font-editorial)' }}
              >
                {c.readNextH2}
              </h2>
            </Reveal>
            <div className="grid gap-6 md:grid-cols-2">
              {related.map((p, i) => (
                <Reveal key={p.slug} delay={(i + 1) as 1 | 2}>
                  <PostCard post={p} variant="editorial" />
                </Reveal>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Dark newsletter + footer, switching out of editorial theme */}
      <div className="bg-night text-snow">
        <Newsletter />
        <Footer />
      </div>
    </div>
  );
}
