import type { PostBlock } from '../data/posts';

interface Props {
  blocks: PostBlock[];
}

/**
 * TableOfContents — extracts H2 headings from post blocks and renders a
 * sticky sidebar. Headings link to anchor ids generated by the Post page.
 * Hidden on small screens — reading long-form on mobile shouldn't fight a
 * sidebar for space.
 */
export default function TableOfContents({ blocks }: Props) {
  const headings = blocks
    .map((b, i) => ({ block: b, index: i }))
    .filter(
      (x): x is { block: Extract<PostBlock, { type: 'heading' }>; index: number } =>
        x.block.type === 'heading' && x.block.level === 2
    );

  if (headings.length < 2) return null;

  return (
    <nav
      aria-label="Table of contents"
      className="hidden xl:block sticky top-24 self-start"
    >
      <p className="text-[10px] uppercase tracking-[0.3em] text-[var(--color-ink-mute)] mb-4 font-semibold">
        In this story
      </p>
      <ul className="space-y-2.5 border-l border-[var(--color-paper-border)]">
        {headings.map(({ block, index }) => {
          const id = `h-${index}`;
          return (
            <li key={id}>
              <a
                href={`#${id}`}
                className="block pl-4 -ml-px border-l-2 border-transparent text-sm text-[var(--color-ink-soft)] hover:text-[var(--color-accent)] hover:border-[var(--color-accent)] transition-colors leading-snug"
              >
                {block.text}
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
